<a href="https://colab.research.google.com/github/happy-table/Machine-Learning/blob/main/Logistic%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving DigitalAd_dataset.csv to DigitalAd_dataset.csv


In [ ]:
digital = pd.read_csv("DigitalAd_dataset.csv")
digital.head()

Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1

In [ ]:
digital.shape

(400, 3)

In [ ]:
x=digital.iloc[:,:-1].values
x

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [ ]:
y=digital.iloc[:,-1].values
y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)
print(x_train.shape)
print(x_test.shape)

(300, 2)
(100, 2)


In [ ]:
from sklearn.preprocessing import StandardScaler #in preprocessing we do scaling,transform,standard
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 0.97446763,  0.56400811],
       [-1.52088611, -1.28151705],
       [ 0.30264162,  0.03671521],
       [-0.36918439, -0.81281224],
       [ 0.49459191,  1.20847722],
       [-0.1772341 ,  0.82765456],
       [-0.27320924, -0.78351819],
       [ 0.39861676,  0.24177356],
       [-0.27320924,  0.00742116],
       [ 0.01471619, -0.60775389],
       [ 0.11069133,  0.00742116],
       [-0.46515953,  2.29235707],
       [ 0.39861676, -0.02187289],
       [-0.27320924, -1.28151705],
       [ 1.93421906, -1.39869325],
       [-0.27320924,  2.23376897],
       [ 0.11069133,  1.03271291],
       [-0.56113467,  1.44282962],
       [ 0.97446763,  1.85294632],
       [ 0.30264162,  0.03671521],
       [-1.13698554, -1.04716465],
       [-0.08125895,  0.27106761],
       [ 0.30264162, -0.54916579],
       [-0.27320924, -0.60775389],
       [ 0.87849248, -1.39869325],
       [ 0.78251734, -0.34410744],
       [-0.46515953, -1.252223  ],
       [ 0.20666648,  0.12459736],
       [ 0.39861676,

In [ ]:
x_test

array([[-1.04101039,  0.73977241],
       [ 0.97446763, -1.1936349 ],
       [ 2.12616935, -1.0764587 ],
       [ 0.97446763,  0.73977241],
       [-0.27320924,  0.18318546],
       [-0.56113467, -1.5451635 ],
       [-0.8490601 , -0.69563604],
       [ 1.83824392,  0.09530331],
       [-0.65710982, -1.63304565],
       [ 0.20666648,  0.03671521],
       [-1.90478668, -0.78351819],
       [-0.8490601 , -0.28551934],
       [-1.13698554, -1.1350468 ],
       [ 0.87849248, -0.60775389],
       [ 1.07044277, -1.252223  ],
       [-0.46515953,  1.23777127],
       [ 0.87849248,  1.23777127],
       [ 0.20666648, -0.69563604],
       [ 0.30264162,  0.27106761],
       [-0.27320924, -0.37340149],
       [-1.32893582,  0.38824381],
       [-0.08125895, -0.02187289],
       [-0.94503525, -0.34410744],
       [ 0.20666648,  0.00742116],
       [-0.94503525, -1.1350468 ],
       [ 0.39861676,  0.12459736],
       [-1.13698554, -1.63304565],
       [-0.65710982, -1.5451635 ],
       [ 1.93421906,

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(x_train,y_train)


LogisticRegression(random_state=0)

In [ ]:

y_pred = model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import accuracy_score
print("accuracy:{0}".format(accuracy_score(y_test,y_pred)*100))

accuracy:80.0
